### ISSUE TITLE
Ichimoku overlay

### ISSUE THREAD

**Issue by khyoz** [tvjsx/trading-vue-js#39]
This is not really a bug, but wanted to open a queue to discuss about the progress of Ichimoku indicator with TVJS.
Code will be shared when a good beta is available and once I checked all the values of all the lines.
This is created with 1 overlay, which calculates and draws all the 5 lines, with options to display each of the line, change the color...
Thanks @C4151 for your 2 latest changes, opening the grid to the future !
Work in Progress

![progress ichimoku 2019-07-21_154808](https://user-images.githubusercontent.com/26684951/61592169-cac50400-abcf-11e9-95c0-a492ca05bc09.png)

**Comment by C451** [comment]
Looks cool! (and scary, Ichimoku always scares the shit out of every minimalist :D ) I have a couple of questions regarding the lib:

- does the chart look blurry on your screen? (I think I solved this, just want to double-check)
- what's up with the cursor, did it disappear for real?

Also one important note: it would be better to separate calculations from the actual overlay, because it is more like a shader. Yes, you can do some light calculations, but for the most part it's just for rendering. In the near future I'll add a special data helper interface for dealing with data. 

You can share a gist with the code if you like (or even create a repo). Would be nice to play!

**Comment by khyoz** [comment]
Screen is not blurry. Cursor is there now, it was a little problem with ctx.stroke function.
Ok if calculations can be done outside of the overlay, so let's just say, this is a beta IKH, prototype. It will be improved in the future.
I think the only problem will be to fill the cloud with a color... I really don't know how to do it right now.
I will share code and data after some additional changes in the next days.

**Comment by C451** [comment]
Good to hear. 

> I think the only problem will be to fill the cloud with a color...

A little bit tricky, but it works: https://github.com/C451/trading-vue-js/blob/master/src/components/overlays/Channel.vue#L25 

I almost came up with a structure for data helper. Basically, each overlay will be able to register additional data calculations (transformations), e.g. ohlc -> ichimoku. 

So, instead of using plain data we could wrap it in a special class `DataHelper` :
```
<trading-vue-js :data="DataHelper(data)"></trading-vue-js>
```
which performs all calculations outside of the overlay.

**Comment by khyoz** [comment]
cool, ok I should be able to fill with color then, but I just thought I needed to restart because in the overlay, currently I only have a range (subset) of data displayed in the screen. That's why I couldn't calculate the lines on the left of the screen.
I guess your datahelper is something like in your tools/og_data.js example
I think I will wait for your DataHelper then, or I will calculate overlays data outside of the overlay.

**Comment by C451** [comment]
> currently I only have a range (subset) of data displayed in the screen. 

Exactly! Overlay maps a subset of data to screen coordinates.

>  think I will wait for your DataHelper then, or I will calculate overlays data outside of the overlay.

You can simply create the function `calc(ohlc) {  ... return ichimoku }` in your app and feed the result to your overlay. When DH is ready, we can just distribute this function with the Ichimoku pack.

> Man, your project opens a lot of possibilities for technical analysis, replay, indicators etc ! I love it !

Thanks! It started kinda random, I was just trying to learn a reactive framework :)

**Comment by C451** [comment]
Yeah, the ichimoku format could be (may be wrong about names):
```
[1555668000000, Kumo, Senkou, Chikou, Kijun, Tenken]
....
[1556287200000, Kumo, undefined, undefined, undefined, undefined]
```
So your overlay will render only Kumo after the chart
